export default [
  {
    name: 'Tyler Thielmann',
    role: 'President',
    email: 'tyler@springfinancial.ca',
    id: 'tyler',
    photo: require('~/assets/Tyler.png'),
  },
  {
    name: 'Victor Ko',
    role: 'VP, Finance & Strategy',
    email: 'victor.ko@springfinancial.ca',
    id: 'victor.ko',
    photo: require('~/assets/Victor.png'),
  },
  {
    name: 'Emily Gardner',
    role: 'Head of Personal Loans',
    email: 'emily.gardner@springfinancial.ca',
    id: 'emily.gardner',
    photo: require('~/assets/Emily.png'),
  },
  {
    name: 'Israel Martinez',
    role: 'Head of Product',
    email: 'israel.martinez@springfinancial.ca',
    id: 'israel.martinez',
    photo: require('~/assets/Israel.png'),
  },
  {
    name: 'Roger Shen',
    role: 'Head of Software Engineering',
    email: 'roger.shen@springfinancial.ca',
    id: 'roger.shen',
    photo: require('~/assets/Roger.png'),
  },
  {
    name: 'Spencer Kong',
    role: 'Program Manager, Credit Solutions',
    email: 'spencer.kong@springfinancial.ca',
    id: 'spencer.kong',
    photo: require('~/assets/Spencer.png'),
  },
  {
    name: 'Laura Marchand',
    role: 'Head of Customer Success',
    email: 'laura.marchand@springfinancial.ca',
    id: 'laura.marchand',
    photo: require('~/assets/Laura.png'),
  },
  {
    name: 'Janessa Ellis',
    role: 'Program Manager, Underwriting',
    email: 'janessa.ellis@springfinancial.ca',
    id: 'janessa.ellis',
    photo: require('~/assets/Janessa.png'),
  },
  {
    name: 'Erin Baile',
    role: 'People Operations Manager',
    email: 'erin.baile@springfinancial.ca',
    id: 'erin.baile',
    photo: require('~/assets/Erin.png'),
  },
  {
    name: 'Henry Dimawala',
    role: 'Head of Customer Retention',
    email: 'henry.dimawala@springfinancial.ca',
    id: 'henry.dimawala',
    photo: require('~/assets/Henry.png'),
  },
  {
    name: 'Aleksandr Aronov',
    role: 'Lead Designer',
    email: 'aleksandr.aronov@springfinancial.ca',
    id: 'aleksandr.aronov',
    photo: require('~/assets/Aleksandr.png'),
  },
  {
    name: 'Sarah Cabaral',
    role: 'Manager, Mortgages',
    email: 'shanna.cabaral@springfinancial.ca',
    id: 'shanna.cabaral',
    photo: require('~/assets/Sarah.png'),
  },
]
